### ISSUE TITLE
树莓派3b+使用此脚本进行安装

### ISSUE THREAD

**Issue by gaoyuke** [linkease/ddnsto_all_in_one_script#1]
树莓派3b+使用此脚本进行安装，提示安装成功，实则过程中报错。
![1](https://user-images.githubusercontent.com/31268133/109598831-0f0ed900-7b55-11eb-8fff-716de873dd17.png)
![2](https://user-images.githubusercontent.com/31268133/109598838-11713300-7b55-11eb-961a-c3e5044f7167.png)

**Comment by hackkyo** [comment]
github上的install.sh是错的

app_arm='ddnsto-arm.ipk'
app_mips='ddnsto-mipsel.ipk'
app_x86='ddnsto-x86.ipk'
app_ui='luci-app-ddnsto_1.0.0-1_all.ipk'
app_lng='luci-i18n-ddnsto-zh-cn_1.0.0-1_all.ipk'

正确应该是
app_arm='ddnsto_arm.ipk'
app_aarch64='ddnsto_aarch64.ipk'
app_mips='ddnsto_mipsel.ipk'
app_x86='ddnsto_x86_64.ipk'
app_ui='luci-app-ddnsto.ipk'
app_lng='luci-i18n-ddnsto-zh-cn.ipk'

**Comment by jannson** [comment]
非常感谢，我马上确认下。

**Comment by gaoyuke** [comment]
楼上说的是对的 koolshare的文件服务器 文件没有版本号后缀，你的脚本里加了后缀，导致无法下载文件。

**Comment by jannson** [comment]
我更新好了。我发现我很早就改好了代码，忘记 push 了。

请重新试试是否能用？
